package main

import (
	"fmt"
	"net/http"
	"io/ioutil"
	"os"
	"encoding/json"
)

func main() {

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	resp, err := http.Get("http://api.giphy.com/v1/gifs/search?q=great+day&api_key=dc6zaTOxFJmzC")
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
	contents, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Printf("%s", err)
		os.Exit(1)
	}
//	fmt.Printf("%s\n", string(contents))
	var f interface{}
	err = json.Unmarshal(contents, &f)

	m := f.(map[string]interface{})
//	fmt.Println(m["data"])
	fmt.Printf("%v\n", m["data"])
	arr := m["data"].([]interface{})

	for index, result := range arr {
		bla := result.(map[string]interface{})
		fmt.Printf("Result[%d] is [%s]\n", index, bla["url"].(string))
	}
}