package main

import (
	"net/http"
	"fmt"
)

func main() {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	resp, err := http.Get("http://api.wunderground.com/auto/wui/geo/ForecastXML/index.xml?query=${@:-19008}")
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
	fmt.Print(resp)
}
